=== h-rajpal/h-rajpal.github.io/extra/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "iso8601": {
      "type": "string",
      "description": "e.g. 2014-06-29",
      "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "description": "link to the version of the schema that can validate the resume",
      "format": "uri"
    },
    "basics": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string",
          "description": "e.g. Web Developer"
        },
        "image": {
          "type": "string",
          "description": "URL (as per RFC 3986) to a image in JPEG or PNG format"
        },
        "email": {
          "type": "string",
          "description": "e.g. thomas@gmail.com",
          "format": "email"
        },
        "phone": {
          "type": "string",
          "description": "Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923"
        },
        "url": {
          "type": "string",
          "description": "URL (as per RFC 3986) to your website, e.g. personal homepage",
          "format": "uri"
        },
        "summary": {
          "type": "string",
          "description": "Write a short 2-3 sentence biography about yourself"
        },
        "location": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "address": {
              "type": "string",
              "description": "To add multiple address lines, use \n. For example, 1234 Glücklichkeit Straße\nHinterhaus 5. Etage li."
            },
            "postalCode": {
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "countryCode": {
              "type": "string",
              "description": "code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN"
            },
            "region": {
              "type": "string",
              "description": "The general region where you live. Can be a US state, or a province, for instance."
            }
          }
        },
        "profiles": {
          "type": "array",
          "description": "Specify any number of social networks that you participate in",
          "additionalItems": false,
          "items": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "network": {
                "type": "string",
                "description": "e.g. Facebook or Twitter"
              },
              "username": {
                "type": "string",
                "description": "e.g. neutralthoughts"
              },
              "url": {
                "type": "string",
                "description": "e.g. http://twitter.example.com/neutralthoughts",
                "format": "uri"
              }
            }
          }
        }
      }
    },
    "work": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "location": {
            "type": "string",
            "description": "e.g. Menlo Park, CA"
          },
          "description": {
            "type": "string",
            "description": "e.g. Social Media Company"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple accomplishments",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            }
          }
        }
      }
    },
    "volunteer": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "organization": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify accomplishments and achievements",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            }
          }
        }
      }
    },
    "education": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "institution": {
            "type": "string",
            "description": "e.g. Massachusetts Institute of Technology"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "area": {
            "type": "string",
            "description": "e.g. Arts"
          },
          "studyType": {
            "type": "string",
            "description": "e.g. Bachelor"
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "score": {
            "type": "string",
            "description": "grade point average, e.g. 3.67/4.0"
          },
          "courses": {
            "type": "array",
            "description": "List notable courses/subjects",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. H1302 - Introduction to American history"
            }
          }
        }
      }
    },
    "awards": {
      "title":"Grants and Awards",
      "type": "array",
      "description": "Specify any awards you have received throughout your professional career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "title": {
            "type": "string",
            "description": "e.g. One of the 100 greatest minds of the century"
          },
          "date": {
            "$ref": "#/definitions/iso8601"
          },
          "awarder": {
            "type": "string",
            "description": "e.g. Time Magazine"
          },
          "summary": {
            "type": "string",
            "description": "e.g. Received for my work with Quantum Physics"
          }
        }
      }
    },
    "certificates": {
      "type": "array",
      "description": "Specify any certificates you have received throughout your professional career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Certified Kubernetes Administrator"
          },
          "date": {
            "type": "string",
            "description": "e.g. 1989-06-12",
            "format": "date"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://example.com",
            "format": "uri"
          },
          "issuer": {
            "type": "string",
            "description": "e.g. CNCF"
          }
        }
      }
    },
    "publications": {
      "type": "array",
      "description": "Specify your publications through your career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "publisher": {
            "type": "string",
            "description": "e.g. IEEE, Computer Magazine"
          },
          "releaseDate": {
            "$ref": "#/definitions/iso8601"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html",
            "format": "uri"
          },
          "summary": {
            "type": "string",
            "description": "Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML."
          },
          "image": {
            "type": "string",
            "description": "URL (as per RFC 3986) to an image from the publication"
          }
        }
      }
    },
    "skills": {
      "type": "array",
      "description": "List out your professional skill-set",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Web Development"
          },
          "level": {
            "type": "string",
            "description": "e.g. Master"
          },
          "keywords": {
            "type": "array",
            "description": "List some keywords pertaining to this skill",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. HTML"
            }
          }
        }
      }
    },
    "languages": {
      "type": "array",
      "description": "List any other languages you speak",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "language": {
            "type": "string",
            "description": "e.g. English, Spanish"
          },
          "fluency": {
            "type": "string",
            "description": "e.g. Fluent, Beginner"
          }
        }
      }
    },
    "interests": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Philosophy"
          },
          "keywords": {
            "type": "array",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Friedrich Nietzsche"
            }
          }
        }
      }
    },
    "references": {
      "type": "array",
      "description": "List references you have received",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Timothy Cook"
          },
          "reference": {
            "type": "string",
            "description": "e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing."
          }
        }
      }
    },
    "projects": {
      "type": "array",
      "description": "Specify career projects",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "description": {
            "type": "string",
            "description": "Short summary of project. e.g. Collated works of 2017."
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple features",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Directs you close but not quite there"
            }
          },
          "keywords": {
            "type": "array",
            "description": "Specify special elements involved",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. AngularJS"
            }
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html"
          },
          "roles": {
            "type": "array",
            "description": "Specify your role on this project or in company",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Team Lead, Speaker, Writer"
            }
          },
          "entity": {
            "type": "string",
            "description": "Specify the relevant company/entity affiliations e.g. 'greenpeace', 'corporationXYZ'"
          },
          "type": {
            "type": "string",
            "description": " e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'"
          }
        }
      }
    },
    "teaching": {
      "type": "array",
      "description": "Specify teaching experience",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "description": {
            "type": "string",
            "description": "Short summary of project. e.g. Collated works of 2017."
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "roles": {
            "type": "array",
            "description": "Specify your role on this project or in company",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Team Lead, Speaker, Writer"
            }
          },
          "entity": {
            "type": "string",
            "description": "Specify the relevant company/entity affiliations e.g. 'greenpeace', 'corporationXYZ'"
          },
          "type": {
            "type": "string",
            "description": " e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'"
          }
        }
      }
    },
    "meta": {
      "type": "object",
      "description": "The schema version and any other tooling configuration lives here",
      "additionalProperties": true,
      "properties": {
        "canonical": {
          "type": "string",
          "description": "URL (as per RFC 3986) to latest version of this document",
          "format": "uri"
        },
        "version": {
          "type": "string",
          "description": "A version field which follows semver - e.g. v1.0.0"
        },
        "lastModified": {
          "type": "string",
          "description": "Using ISO 8601 with YYYY-MM-DDThh:mm:ss"
        }
      }
    }
  },
  "title": "Resume Schema",
  "type": "object"
}

=== h-rajpal/h-rajpal.github.io/data/json_resume/en.json
{
  "$schema": "https://raw.githubusercontent.com/h-rajpal/h-rajpal.github.io/main/extra/schema.json",
  "basics": {
    "name": "Hardik Rajpal",
    "label": "Eric and Wendy Schmidt\nAI in Science Fellow",
    "image": "https://raw.githubusercontent.com/h-rajpal/h-rajpal.github.io/main/images/profile.jpg",
    "email": "h.rajpal15@imperial.ac.uk",
    "summary": "A complexity scientist on the quest to understand the principles of biological, social and artificial intelligence.",
    "location": {
      "city": "London"
    },
    "profiles": [
      {
        "network": "GitHub",
        "url": "https://github.com/h-rajpal"
      },
      {
        "network": "X",
        "url": "https://x.com/pixelated_poet"
      },
      {
        "network": "bluesky",
        "url": "https://bsky.app/profile/h-rajpal.bsky.social"
      }
    ]
  },
  "work": [
    {
      "name": "I-X Imperial College London",
      "location": "London, UK",
      "position": "AI in Science Research Fellow",
      "url": "https://profiles.imperial.ac.uk/h.rajpal15",
      "startDate": "2025-10-01",
      "endDate": "2027-09-30",
      "summary": "Exploring the role of self-organization and emergence in task-generalization and learning in artificial and biological neural networks."
    },
    {
      "name": "Mathematics, Imperial College London",
      "location": "London, UK",
      "position": "Postdoctoral Researcher",
      "url": "https://profiles.imperial.ac.uk/h.rajpal15",
      "startDate": "2023-04-01",
      "endDate": "2025-09-30",
      "summary": "Statistical Physics of Cognition project focused on investigationg the role of critical brain dynamics in cognition using experimental, mathematical and computational methods."
    },
    {
      "name": "The Alan Turing Institute",
      "location": "London, UK",
      "position": "Postdoctoral Researcher",
      "url": "https://www.turing.ac.uk/people/researchers/hardik-rajpal",
      "startDate": "2021-07-26",
      "endDate": "2023-03-31",
      "summary": "The Shocks and Resilience project was an interdisciplinary research project exploring resilience in health, economic and online social systems."
    },
    {
      "name": "BIOS Health Ltd.",
      "location": "Cambridge, UK",
      "position": "PhD Intern",
      "url": "https://www.bios.health",
      "startDate": "2020-02-28",
      "endDate": "2021-03-15",
      "summary": "BIOS Health is a research intensive healthtech startup based in Cambridge. They are a pioneering AI driven neural-interface devices to develop targetted therapies for chronic illnesses."
    }
  ],
  "volunteer": [
    {
      "organization": "CoderDojo",
      "position": "Teacher",
      "url": "http://coderdojo.example.com/",
      "startDate": "2012-01-01",
      "endDate": "2013-01-01",
      "summary": "Global movement of free coding clubs for young people.",
      "highlights": ["Awarded 'Teacher of the Month'"]
    }
  ],
  "education": [
    {
      "institution": "Imperial College London",
      "url": "https://www.imperial.ac.uk/",
      "area": "Applied Mathematics",
      "studyType": "PhD",
      "startDate": "2017-09-30",
      "endDate": "2021-10-01",
      "dissertation": "Causality and Emergence in Complex Systems: Perspectives from Information Theory"
    },
    {
      "institution": "Indian Institute of Technology Kharagpur",
      "url": "https://www.iitkgp.ac.in/",
      "area": "Physics",
      "studyType": "Integrated MSc",
      "startDate": "2012-07-20",
      "endDate": "2017-08-30",
      "dissertation": "On the dynamics of parametrically forced oscillations in a damped planar double pendulum"
    }
  ],
  "awards": [
    {
      "title": "Best Poster Award",
      "date": "2024-07-10",
      "awarder": "UK Neural Computation Conference 2024",
      "summary": "Awarded for the poster \"Are Brain Oscillations Emergent?\""
    },
    {
      "title": "Mathematics Small Grants Award",
      "date": "2022-03-01",
      "awarder": "Engineering and Physical Sciences Research Council (EPSRC)",
      "summary": "Co wrote the proposal for the \"Quantifying Agency in Time Evolving Systems\" as the named researcher."
    },
    {
      "title": "President's PhD Scholarship",
      "date": "2017-10-01",
      "awarder": "Imperial College London",
      "summary": "Awarded Scholarship to pursue a PhD in Applied Mathematics at the Centr for Complexity Sciences, Imperial College."
    },
    {
      "title": "Innovation in Science Pursuit for Inspired Research (INSPIRE) Fellowship",
      "date": "2012-07-20",
      "awarder": "Department of Science and Technology, Government of India",
      "summary": "Awarded for pursuing research in Natural Sciences at the undergraduate level."
    }
    
  ],
  "publications": [
    {
      "name": "Psychedelics and schizophrenia: Distinct alterations to Bayesian inference",
      "publisher": "Neuroimage",
      "authors": "Hardik Rajpal, Pedro AM Mediano, Fernando E Rosas, Christopher B Timmermann, Stefan Brugger, Suresh Muthukumaraswamy, Anil K Seth, Daniel Bor, Robin L Carhart-Harris, Henrik J Jensen",
      "releaseDate": "2022-11-01",
      "url": "https://doi.org/10.1016/j.neuroimage.2022.119624"
    },
    {
      "name": "Tangled worldview model of opinion dynamics",
      "publisher": "Frontiers in Physics",
      "authors": "Hardik Rajpal, Fernando E Rosas, Henrik J Jensen",
      "releaseDate": "2019-10-25",
      "url": "https://doi.org/10.3389/fphy.2019.00163"
    },
    {
      "name": "Synergistic Small Worlds that Drive Technological Sophistication",
      "publisher": "arXiv",
      "authors": "Hardik Rajpal, Omar A Guerrero",
      "releaseDate": "2023-01-11",
      "url": "https://arxiv.org/abs/2301.04579"
    },
    {
      "name": "Quantifying Hierarchical Selection",
      "publisher": "arXiv",
      "authors": "Hardik Rajpal, Clem von Stengel, Pedro AM Mediano, Fernando E Rosas, Eduardo Viegas, Pablo A Marquet, Henrik J Jensen",
      "releaseDate": "2023-10-31",
      "url": "https://arxiv.org/abs/2310.20386"
    }
    
  ],
  "skills": [
    {
      "name": "Web Development",
      "level": "Master",
      "keywords": ["HTML", "CSS", "Javascript"]
    },
    {
      "name": "Compression",
      "level": "Master",
      "keywords": ["Mpeg", "MP4", "GIF"]
    }
  ],
  "languages": [
    {
      "language": "English",
      "fluency": "Native speaker"
    }
  ],
  "interests": [
    {
      "name": "Wildlife",
      "keywords": ["Ferrets", "Unicorns"]
    }
  ],
  "references": [
    {
      "name": "Erlich Bachman",
      "reference": "It is my pleasure to recommend Richard, his performance working as a consultant for Main St. Company proved that he will be a valuable addition to any company."
    }
  ],
  "projects": [
    {
      "name": "Miss Direction",
      "description": "A mapping engine that misguides you",
      "highlights": [
        "Won award at AIHacks 2016",
        "Built by all women team of newbie programmers",
        "Using modern technologies such as GoogleMaps, Chrome Extension and Javascript"
      ],
      "keywords": ["GoogleMaps", "Chrome Extension", "Javascript"],
      "startDate": "2016-08-24",
      "endDate": "2016-08-24",
      "roles": ["Team lead", "Designer"],
      "entity": "Smoogle",
      "type": "application"
    }
  ],
  "teaching": [ 
    {
    "name": "Complexity and Networks Lab, Imperial College London",
    "role": "Lab Demonstrator",
    "startDate": "2020-01-10",
    "endDate": "2020-03-31",
    "summary": "Assisted students in hands-on tutorials focused on modelling self-organized criticality, generating scale-free network topology and numerical analysis."
  },
  {
    "name": "Department of Mathematics, Imperial College London",
    "role": "MSc & UG Supervisor",
    "startDate": "2019-01-10",
    "endDate": "2024-08-31",
    "summary": "Supervised multiple Masters and Undergraduate students, interested in pursuing a dissertation in the field of complexity, networks and neuroscience."
  }
  ],
  "meta": {
    "canonical": "https://raw.githubusercontent.com/jsonresume/resume-schema/master/resume.json",
    "version": "v1.0.0",
    "lastModified": "2017-12-24T15:53:00"
  }
}
